name: if Expression

on:
    push

jobs:
  testing:
    name: Testing Application
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 0.5
    continue-on-error: true
    steps:
    - name: Test for ubuntu
      if: runner.os == 'Linux'
      run: |
        echo "Running Test for Ubuntu .... "

    - name: Test for Windows
      if: runner.os == 'Windows'
      run: |
        echo "Running Test for Windows .... "

  report:
    needs: testing
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - name: Upload Image to AWS S3 bucket
      run: | 
        echo "Uploading Image ..... " && exit 1

  deploy: 
    needs: report
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Image 
      run: |
        echo "Deploying Image .... "
